### ISSUE TITLE
Regarding 1st step pre-training

### ISSUE THREAD

**Issue by ChengFu0118** [ychzhang/fracbnn#1]
Dear author,

Thanks so much for sharing your code! I have a small question regarding the 1st step pre-training. By simply change FastSign() into nn.sequential() (as you indicated), the following module will binarize neither the inputs nor weights. Do you mean to change self.binarize(self.weight) to self.weight  in the PGBinaryConv2d?https://github.com/ychzhang/fracbnn/blob/4edca5815d1504e8a0ce97c6735d1edcb2d5531a/utils/quantization.py#L173

**Comment by ychzhang** [comment]
Yes, right. We should modify self.binarize(self.weight) to self.weight in the PGBinaryConv2d in the first step. Thanks for correcting it!
I'm going to soon push a new commit that corrects the Readme document.
